---
- name: Check NginX logrotate conf
  hosts: all
  become: yes
  tasks:

    - name: Get NginX logrotate conf
      shell: cat /etc/logrotate.d/nginx
      register: logrotate_conf

    - name: Show logrotate conf
      debug:
        msg: "NginX logrotate conf is {{ logrotate_conf.stdout }}%"
