- name: Play 1
  hosts: all
  gather_facts: true
  become: true
  tasks:
 - name: Print a host variable inventory host
    debug:
      var: inventory_hostname
      
     - name: Who am I
       ansible.builtin.command: whoami
       register: _command

     - name: debug
       ansible.builtin.debug:
         var: _command
